### ISSUE TITLE
prvTidyParseNamespace: Assertion `outside == no ? n == mp : 1' failed (parser.c:1559)

### ISSUE THREAD

**Issue by geeknik** [htacg/tidy-html5#369]
While fuzzing tidy-html5 with AFL, I found the following HTML snippet:

`<math
</html>`

which triggers this assertion failure:

valgrind -q  ~/tidy-html5/build/cmake/tidy test01.html
```
line 1 column 1 - Warning: <math> missing '>' for end of tag
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: missing </body> before <math>
tidy: /home/geeknik/tidy-html5/src/parser.c:1559: prvTidyParseNamespace: Assertion `outside == no ? n == mp : 1' failed.
Aborted
```

(gdb) r test01.html
```
Starting program: /home/geeknik/tidy-html5/build/cmake/tidy test01.html
line 1 column 1 - Warning: <math> missing '>' for end of tag
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: missing </body> before <math>
tidy: /home/geeknik/tidy-html5/src/parser.c:1559: prvTidyParseNamespace: Assertion `outside == no ? n == mp : 1' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7a84165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7a84165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff7a873e0 in *__GI_abort () at abort.c:92
#2  0x00007ffff7a7d311 in *__GI___assert_fail (
    assertion=assertion@entry=0x595f9b "outside == no ? n == mp : 1", file=<optimized out>,
    file@entry=0x595ef8 "/home/geeknik/tidy-html5/src/parser.c", line=line@entry=1559,
    function=function@entry=0x596020 "prvTidyParseNamespace") at assert.c:81
#3  0x0000000000489d11 in prvTidyParseNamespace (doc=0x7cc010, basenode=0x7d04f0, mode=OtherNamespace)
    at /home/geeknik/tidy-html5/src/parser.c:1559
#4  0x000000000049d923 in ParseTag (mode=MixedContent, node=0x7d04f0, doc=0x7cc010)
    at /home/geeknik/tidy-html5/src/parser.c:775
#5  prvTidyParseBody (doc=0x7cc010, body=0x7d0300, mode=<optimized out>)
    at /home/geeknik/tidy-html5/src/parser.c:4085
#6  0x00000000004a3fa2 in prvTidyParseDocument (doc=doc@entry=0x7cc010)
    at /home/geeknik/tidy-html5/src/parser.c:4763
#7  0x0000000000454642 in prvTidyDocParseStream (doc=doc@entry=0x7cc010, in=in@entry=0x7d0670)
    at /home/geeknik/tidy-html5/src/tidylib.c:1266
#8  0x0000000000455263 in tidyDocParseFile (filnam=<optimized out>, doc=0x7cc010)
    at /home/geeknik/tidy-html5/src/tidylib.c:929
#9  tidyParseFile (tdoc=tdoc@entry=0x7cc010, filnam=filnam@entry=0x7fffffffe887 "test01.html")
    at /home/geeknik/tidy-html5/src/tidylib.c:877
#10 0x000000000040cbbf in main (argc=2, argv=0x7fffffffe648)
    at /home/geeknik/tidy-html5/console/tidy.c:1901
```

**Comment by geoffmcl** [comment]
@geeknik thanks for the report. All I can comment at this stage is that that assert is indeed fired using your sample!

As I am sure you are aware asserts only existing in the debug version, as a debug aid mostly, and to remove them you need to add `-DCMAKE_BUILD_TYPE=Release`. In other words, they do not exist in the Released version of the library.

If I remember correctly the initial MathML support came from @GerHobbelt, from https://github.com/GerHobbelt/htmltidy, I think, or maybe others - it was certainly not written by me - see #70 and #130 - so I am unsure of the reason, or meaning, for that particular assert... maybe he or others can comment...

In a quick test, removing it seems to have no adverse consequences, but hope others can comment on this...

**Comment by geoffmcl** [comment]
@geeknik, as suggested I can see no problem with removing these Debug only asserts, but as indicated would love to hear from the original author of the code, or from others...

````
diff --git a/src/parser.c b/src/parser.c
index 2d9de5c..0447fe8 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -1564,8 +1564,13 @@ void TY_(ParseNamespace)(TidyDocImpl* doc, Node *basenode, GetTokenMode mode)
                     n->closed = yes;
                     TY_(ReportError)(doc, n->parent, n, MISSING_ENDTAG_BEFORE);
                 }
-                assert(outside == no ? n == mp : 1);
-                assert(outside == yes ? n == basenode->parent : 1);
+
+                /* Issue #369 - Since 'assert' is DEBUG only, and there are
+                   simple cases where these can be fired, removing them
+                   pending feedback from the original author!
+                   assert(outside == no ? n == mp : 1);
+                   assert(outside == yes ? n == basenode->parent : 1);
+                   =================================================== */
 
                 if (outside == no)
                 {
````

I will continue testing this, but meantime we are considering a release 5.2 shortly, so resetting the milestone to 5.3.

If you or others can make time to test with this patch, and report, maybe it could still be included in 5.2...

**Comment by geoffmcl** [comment]
@geeknik I have done further testing of this removal, and can sse no problem doing it, but as noted, subject to any feedback from the original author...

Have bumped the version to 5.1.51... Appreciated if you could pull the latest `master` and retest the DEBUG version... and close if ok... thanks...

**Comment by geoffmcl** [comment]
@geeknik this is now in release 5.2, and no reported problems... well it only effects the debug version in any case... so am closing this...

Please feel free to re-open, or file a new issue... thanks for your support...
